services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fa
    container_name: gym_fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network

  dashboard:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dashboard
    container_name: gym_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
