name: CI/CD Pipeline with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: docker-deploy   # <- Use the environment

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push FastAPI Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.fa
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlops-mini-project-fastapi:latest

      - name: Build and push Dashboard Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: Dockerfile.dashboard
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlops-mini-project-dashboard:latest
