name: CI/CD Pipeline with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Docker Hub secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_PASSWORD }}" ]; then
            echo "ERROR: Missing Docker Hub secrets. Please add DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD to repository secrets."
            exit 1
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push FastAPI image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.fa
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-mini-project-fastapi:latest
          platforms: linux/amd64

      - name: Build and push Dashboard image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: Dockerfile.dashboard
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-mini-project-dashboard:latest
          platforms: linux/amd64
