name: CI/CD Pipeline with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push FastAPI Docker image
      - name: Build and push FastAPI image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.fa
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-mini-project-fastapi:latest

      # Step 4: Build and push Streamlit Dashboard Docker image
      - name: Build and push Dashboard image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: Dockerfile.dashboard
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-mini-project-dashboard:latest
